# Generated by Django 5.1.6 on 2025-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
