# Generated by Django 5.1.6 on 2025-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='approve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lines',
            name='approve_date',
            field=models.DateField(null=True),
        ),
    ]
