# Generated by Django 5.1.6 on 2025-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_approve_date_lines_approve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='check_14_days',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lines',
            name='check_14_days',
            field=models.BooleanField(default=True),
        ),
    ]
