# Generated by Django 5.1.6 on 2025-05-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_check_14_days_lines_check_14_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='volttage_level',
            new_name='voltage_level',
        ),
    ]
