# Generated by Django 5.1.6 on 2025-02-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('voltage_level', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regions.acc')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regions.region')),
            ],
        ),
    ]
