# Generated by Django 5.1.6 on 2025-02-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=1024)),
                ('rom_name', models.CharField(max_length=128)),
                ('rom_email', models.EmailField(max_length=254)),
                ('rom_phone', models.CharField(max_length=20)),
                ('roc_name', models.CharField(max_length=128)),
                ('roc_email', models.EmailField(max_length=254)),
                ('roc_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='regions.region')),
            ],
        ),
    ]
