# Generated by Django 5.1.6 on 2025-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
