# Generated by Django 5.1.6 on 2025-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='short_code',
            field=models.CharField(max_length=20),
        ),
    ]
