# Generated by Django 5.1.6 on 2025-03-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('requests', '0002_alter_request_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='request',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.lines'),
        ),
    ]
