# Generated by Django 5.1.6 on 2025-03-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_equipment_alter_request_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='seen_by_approval',
            field=models.BooleanField(default=False),
        ),
    ]
