# Generated by Django 5.1.6 on 2025-03-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_request_approve_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='outage_type',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
