# Generated by Django 5.1.6 on 2025-03-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_request_outage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='area_affected',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='disco_genco_notified',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
