# Generated by Django 5.1.6 on 2025-04-26 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_request_area_affected_request_disco_genco_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.CharField(editable=False, help_text='Custom request identifier like REQ-00001 or REQ-<UUID>', max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique log entry ID', primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='requests.request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
