# Generated by Django 5.1.6 on 2025-04-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_request_request_id_requestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dota',
            field=models.IntegerField(default=0, help_text='Number of times disapproved'),
        ),
        migrations.AddField(
            model_name='request',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='execution_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='nota',
            field=models.IntegerField(default=0, help_text='Number of times approved'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.CharField(editable=False, help_text='Custom request identifier like REQ-00001 or REQ-<UUID>', max_length=40, unique=True),
        ),
    ]
