# Generated by Django 5.1.6 on 2025-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_request_dota_request_executed_at_request_executed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='custom_equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='custom_line_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
