# Generated by Django 5.1.6 on 2025-05-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_request_custom_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reason_submission_issues',
            field=models.TextField(null=True),
        ),
    ]
