# Generated by Django 5.1.6 on 2025-08-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_request_reason_submission_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
